//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalBlockLabels.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerminalBlockLabels.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to REF2,LOC1,LOC2,WIRENO,WLAY1,REF1
        ///124,CP POWER,CONTROL PANEL,3111,BLU_16AWG,121
        ///654,CP POWER,CONTROL PANEL,3112,WHT_BLU_16AWG,245
        ///876,CP DOOR,CONTROL PANEL,1171,RED_16AWG,234
        ///987,CP FSG,CONTROL PANEL,2091,VT_16AWG,121
        ///.
        /// </summary>
        internal static string AutoCADFileWithHeadersOutOfOrder
        {
            get
            {
                return ResourceManager.GetString("AutoCADFileWithHeadersOutOfOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOC2,WIRENO,WLAY1
        ///CONTROL PANEL,3111,BLU_16AWG
        ///.
        /// </summary>
        internal static string AutoCADFileWithMissingHeader
        {
            get
            {
                return ResourceManager.GetString("AutoCADFileWithMissingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOC1,LOC2,WIRENO,WLAY1
        ///CP POWER,CONTROL PANEL,,BLU_16AWG
        ///.
        /// </summary>
        internal static string AutoCADFileWithMissingWireNumber
        {
            get
            {
                return ResourceManager.GetString("AutoCADFileWithMissingWireNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOC1,LOC2,WIRENO,WLAY1,REF1,REF2
        ///CP POWER,CONTROL PANEL,3111,BLU_16AWG,121,124
        ///CP POWER,CONTROL PANEL,3112,WHT_BLU_16AWG,245,654
        ///CP DOOR,CONTROL PANEL,1171,RED_16AWG,234,876
        ///CP FSG,CONTROL PANEL,2091,VT_16AWG,121,987
        ///.
        /// </summary>
        internal static string AutoCADFileWithTooManyHeaders
        {
            get
            {
                return ResourceManager.GetString("AutoCADFileWithTooManyHeaders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOC2,WIRENO,WLAY1,LOC1
        ///CONTROL PANEL,3111,BLU_16AWG,CP POWER
        ///.
        /// </summary>
        internal static string ValidAutoCADFile
        {
            get
            {
                return ResourceManager.GetString("ValidAutoCADFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOC1,LOC2,WIRENO,WLAY1
        ///CP POWER,CONTROL PANEL,3111,BLU_16AWG
        ///CP POWER,CONTROL PANEL,3112,WHT_BLU_16AWG
        ///CP DOOR,CONTROL PANEL,1171,RED_16AWG
        ///CP FSG,CONTROL PANEL,2091,VT_16AWG
        ///.
        /// </summary>
        internal static string ValidAutoCADFileWithMultipleWires
        {
            get
            {
                return ResourceManager.GetString("ValidAutoCADFileWithMultipleWires", resourceCulture);
            }
        }
    }
}